
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ACTA
{

    public int Act_id { get; set; }

    public string Act_UsuarioGenera { get; set; }

    public Nullable<System.DateTime> Act_FechaGenera { get; set; }

    public string Act_Nombre { get; set; }

    public string Act_Direccion { get; set; }

    public string Act_ubicacion { get; set; }

    public Nullable<int> Act_CustodioId { get; set; }

}

}
