
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ACTIVO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ACTIVO()
    {

        this.CARACTERISTICAs = new HashSet<CARACTERISTICA>();

        this.DEPRECIACIONs = new HashSet<DEPRECIACION>();

        this.DEPRECIACIONSRIs = new HashSet<DEPRECIACIONSRI>();

        this.MANTENIMIENTOes = new HashSet<MANTENIMIENTO>();

    }


    public int ACT_ID { get; set; }

    public string EMP_ID { get; set; }

    public System.DateTime ACT_FECHACREACION { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINIDEPRE { get; set; }

    public Nullable<bool> ACT_DEPRECIABLESRI { get; set; }

    public Nullable<bool> ACT_DEPRECIABLE { get; set; }

    public Nullable<bool> ACT_DEPRECIADOSRI { get; set; }

    public Nullable<bool> ACT_DEPRECIADONIIF { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINIOPER { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINIDEPRENIIF { get; set; }

    public Nullable<System.DateTime> ACT_FECHABAJA { get; set; }

    public string USERNAME { get; set; }

    public string ACT_TIPO { get; set; }

    public string ACT_CODBARRAS { get; set; }

    public string ACT_CODBARRASPADRE { get; set; }

    public string ACT_CODIGO1 { get; set; }

    public int GRU_ID1 { get; set; }

    public int GRU_ID2 { get; set; }

    public int GRU_ID3 { get; set; }

    public string ACT_FOTO1 { get; set; }

    public string ACT_FOTO2 { get; set; }

    public string ACT_DOC1 { get; set; }

    public string ACT_DOC2 { get; set; }

    public int UGE_ID1 { get; set; }

    public int UGE_ID2 { get; set; }

    public int UGE_ID3 { get; set; }

    public int UGE_ID4 { get; set; }

    public int UOR_ID1 { get; set; }

    public int UOR_ID2 { get; set; }

    public int UOR_ID3 { get; set; }

    public int CUS_ID1 { get; set; }

    public Nullable<int> CUS_ID2 { get; set; }

    public int EST_ID1 { get; set; }

    public Nullable<int> EST_ID2 { get; set; }

    public Nullable<int> EST_ID3 { get; set; }

    public int MAR_ID { get; set; }

    public int MOD_ID { get; set; }

    public string ACT_SERIE1 { get; set; }

    public Nullable<int> COL_ID { get; set; }

    public Nullable<int> ECO_ID1 { get; set; }

    public Nullable<int> ECO_ID2 { get; set; }

    public Nullable<int> PRO_ID { get; set; }

    public string ACT_TIPOING { get; set; }

    public Nullable<decimal> ACT_NUMFACT { get; set; }

    public Nullable<System.DateTime> ACT_FECHACOMPRA { get; set; }

    public Nullable<decimal> ACT_VALORCOMPRA { get; set; }

    public Nullable<int> ACT_ANIO { get; set; }

    public Nullable<int> ACT_VIDAUTIL { get; set; }

    public Nullable<int> ACT_VIDAUTILNIIF { get; set; }

    public Nullable<decimal> ACT_VALORRESIDUALNIIF { get; set; }

    public Nullable<bool> ACT_GARANTIA { get; set; }

    public Nullable<System.DateTime> ACT_FECHAGARANTIAVENCE { get; set; }

    public string ACT_OBSERVACIONES { get; set; }

    public bool ACT_TRANSFEROK { get; set; }

    public Nullable<int> ACT_PPC { get; set; }

    public string ACT_H1 { get; set; }

    public string ACT_H2 { get; set; }

    public string ACT_PE { get; set; }

    public string ACT_OBSERVACIONES2 { get; set; }

    public Nullable<int> ACT_TIPOBAJA { get; set; }

    public string ACT_OBSBAJA { get; set; }

    public Nullable<bool> ACT_BAJAPROCESADA { get; set; }

    public Nullable<bool> ACT_BAJAPROCESADASRI { get; set; }

    public string ACT_RESUMEN { get; set; }

    public Nullable<decimal> ACT_VALORREPO { get; set; }

    public Nullable<decimal> ACT_VALORRAZONABLE { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINVENTARIO { get; set; }

    public string ACT_CODRFID { get; set; }

    public string ACT_STRADICIONAL3 { get; set; }

    public string ACT_RETIQUETAR { get; set; }

    public Nullable<int> ACT_AUTRFID { get; set; }

    public Nullable<int> ACT_FILRFID { get; set; }

    public Nullable<int> ACT_TIPRFID { get; set; }

    public string ACT_SEGURO { get; set; }

    public Nullable<int> ACT_TIPOSEGURO { get; set; }

    public string ACT_ESTADOMANT { get; set; }

    public Nullable<System.DateTime> ACT_FECHAENVIOMANT { get; set; }

    public Nullable<System.DateTime> ACT_FECHAREGRESOMANT { get; set; }

    public string ACT_DESCRIPCIONLARGA { get; set; }

    public string ACT_NUMPOLIZA { get; set; }

    public Nullable<int> ACT_VIGENCIAPOLIZAMESES { get; set; }

    public Nullable<System.DateTime> ACT_FECHAEMISIONPOLIZA { get; set; }

    public Nullable<System.DateTime> ACT_FECHAVENCEPOLIZA { get; set; }

    public Nullable<decimal> ACT_VALORASEGURADO { get; set; }



    public virtual COLOR COLOR { get; set; }

    public virtual CUSTODIO CUSTODIO { get; set; }

    public virtual ESTRUCOMP ESTRUCOMP { get; set; }

    public virtual ESTRUCOMP ESTRUCOMP1 { get; set; }

    public virtual ESTADO ESTADO { get; set; }

    public virtual ESTADO ESTADO1 { get; set; }

    public virtual GRUPO GRUPO { get; set; }

    public virtual GRUPO GRUPO1 { get; set; }

    public virtual GRUPO GRUPO2 { get; set; }

    public virtual MARCA MARCA { get; set; }

    public virtual MODELO MODELO { get; set; }

    public virtual PROVEEDOR PROVEEDOR { get; set; }

    public virtual TIPO_SEGURO TIPO_SEGURO { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA1 { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA2 { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA3 { get; set; }

    public virtual UORGANICA UORGANICA { get; set; }

    public virtual UORGANICA UORGANICA1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CARACTERISTICA> CARACTERISTICAs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DEPRECIACION> DEPRECIACIONs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DEPRECIACIONSRI> DEPRECIACIONSRIs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MANTENIMIENTO> MANTENIMIENTOes { get; set; }

}

}
