
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cabecera
{

    public int id { get; set; }

    public int IdCabeceraModulo { get; set; }

    public System.DateTime FechaContable { get; set; }

    public short SucursalOrigen { get; set; }

    public decimal TotalDebitoMn { get; set; }

    public decimal TotalDebitoMe { get; set; }

    public decimal TotalCreditoMn { get; set; }

    public decimal TotalCreditoMe { get; set; }

    public short Registros { get; set; }

    public string Digitador { get; set; }

    public string Autorizador { get; set; }

    public string EstadoProceso { get; set; }

    public int LocalidadOrigen { get; set; }

    public int ResponsableOrigen { get; set; }

    public Nullable<int> ModuloCobis { get; set; }

}

}
