
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CARACTERISTICA
{

    public int CAR_ID { get; set; }

    public int ACT_ID { get; set; }

    public int CFA_ID { get; set; }

    public string CAR_VALOR { get; set; }

    public Nullable<int> UNI_ID { get; set; }

    public string CAR_DEL { get; set; }



    public virtual CFAMILIA CFAMILIA { get; set; }

    public virtual UNIDAD UNIDAD { get; set; }

    public virtual ACTIVO ACTIVO { get; set; }

}

}
