
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CFAMILIA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CFAMILIA()
    {

        this.CARACTERISTICAs = new HashSet<CARACTERISTICA>();

    }


    public int CFA_ID { get; set; }

    public int GRU_ID { get; set; }

    public string CFA_NOMBRE { get; set; }

    public int CFA_ORDEN { get; set; }

    public bool CFA_UNIDADES { get; set; }

    public string CFA_OBLIGATORIO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CARACTERISTICA> CARACTERISTICAs { get; set; }

    public virtual GRUPO GRUPO { get; set; }

}

}
