
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CODIGO
{

    public string EMP_ID { get; set; }

    public string COD_PREFIJO { get; set; }

    public string COD_SUFIJO { get; set; }

    public int COD_SECUENCIAL { get; set; }

    public int COD_VERIFICADOR { get; set; }

}

}
