
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CUSTODIO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CUSTODIO()
    {

        this.XCUORs = new HashSet<XCUOR>();

        this.ACTIVOes = new HashSet<ACTIVO>();

    }


    public int CUS_ID { get; set; }

    public string CUS_CODIGO { get; set; }

    public string CUS_APELLIDOS { get; set; }

    public string CUS_NOMBRES { get; set; }

    public string CUS_CEDULA { get; set; }

    public string CUS_TELEFONOFIJO { get; set; }

    public string CUS_EXT { get; set; }

    public string CUS_CELULAR { get; set; }

    public string CUS_FOTO { get; set; }

    public string CUS_EMAIL { get; set; }

    public Nullable<int> CGO_ID { get; set; }

    public string CUS_ESTADO { get; set; }



    public virtual CARGO CARGO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<XCUOR> XCUORs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes { get; set; }

}

}
