
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DEPRECIACIONSRI
{

    public int DEP_ID { get; set; }

    public int DEP_VIDAUTIL { get; set; }

    public decimal DEP_VALORRESIDUAL { get; set; }

    public decimal DEP_SALDOXDEPRE { get; set; }

    public decimal DEP_DEPREACUM { get; set; }

    public int DEP_PERTRANS { get; set; }

    public int DEP_PERREMA { get; set; }

    public decimal DEP_DEPREPERIODO { get; set; }

    public Nullable<System.DateTime> DEP_FECHAPROX { get; set; }

    public string DEP_TIPO { get; set; }

    public int ACT_ID { get; set; }

    public string DEP_CCOSTO { get; set; }

    public string DEP_GRUPO { get; set; }

    public string DEP_OBS { get; set; }

    public Nullable<bool> DEP_BAJA { get; set; }

    public Nullable<System.DateTime> DEP_FECHABAJA { get; set; }



    public virtual ACTIVO ACTIVO { get; set; }

}

}
