
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleModulo
{

    public int id { get; set; }

    public int IdCabeceraModulo { get; set; }

    public int Registro { get; set; }

    public string Cuenta { get; set; }

    public byte IdMoneda { get; set; }

    public short SucursalDestino { get; set; }

    public string Detalle { get; set; }

    public decimal DebitoMn { get; set; }

    public decimal DebitoMe { get; set; }

    public decimal CreditoMn { get; set; }

    public decimal CreditoMe { get; set; }

    public string TipoTransaccion { get; set; }

    public string TipoNegociacion { get; set; }

    public string Operacion { get; set; }

    public string Referencia { get; set; }

    public int LocalidadDestino { get; set; }

    public int ResponsableDestino { get; set; }

}

}
