
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DGENERADASRI
{

    public int DGE_ID { get; set; }

    public System.DateTime DGE_GENERADA { get; set; }

    public System.DateTime DGE_SIGUIENTE { get; set; }

    public string DGE_TIPO { get; set; }

    public string DGE_USUARIO { get; set; }

}

}
