
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GRUPO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GRUPO()
    {

        this.CFAMILIAs = new HashSet<CFAMILIA>();

        this.PROVEEDORs = new HashSet<PROVEEDOR>();

        this.ACTIVOes = new HashSet<ACTIVO>();

        this.ACTIVOes1 = new HashSet<ACTIVO>();

        this.ACTIVOes2 = new HashSet<ACTIVO>();

    }


    public int GRU_ID { get; set; }

    public string GRU_NOMBRE { get; set; }

    public int GRU_PADRE { get; set; }

    public int GRU_NIVEL { get; set; }

    public string GRU_CODIGO { get; set; }

    public string GRU_CTA1 { get; set; }

    public string GRU_CTA2 { get; set; }

    public string GRU_CTA3 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CFAMILIA> CFAMILIAs { get; set; }

    public virtual GRUPOSRI GRUPOSRI { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROVEEDOR> PROVEEDORs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes2 { get; set; }

}

}
