
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HCODIGO
{

    public int HCO_ID { get; set; }

    public System.DateTime HCO_FECHA { get; set; }

    public string HCO_USUARIO { get; set; }

    public string HCO_TIPO { get; set; }

    public string HCO_COD1 { get; set; }

    public string HCO_COD2 { get; set; }

    public int HCO_NUMERO { get; set; }

}

}
