
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HFOTO
{

    public int HFO_ID { get; set; }

    public System.DateTime HFO_FECHA { get; set; }

    public string USERNAME { get; set; }

    public int ACT_ID { get; set; }

    public string HFO_FOTO1 { get; set; }

    public string HFO_FOTO2 { get; set; }

    public string CUS_ID1 { get; set; }

    public string CUS_ID2 { get; set; }

    public string HFO_FOTO3 { get; set; }

}

}
