
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HISTORIAL_PASSWORD
{

    public int Id { get; set; }

    public string usuario { get; set; }

    public string password { get; set; }

    public System.DateTime fechacreacion { get; set; }

    public int cont { get; set; }

}

}
