
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HUCUSTODIO
{

    public int HUC_ID { get; set; }

    public string USERNAME { get; set; }

    public System.DateTime HUC_FECHA { get; set; }

    public int ACT_ID { get; set; }

    public string UGE_ID1 { get; set; }

    public string UGE_ID2 { get; set; }

    public string UGE_ID3 { get; set; }

    public string UGE_ID4 { get; set; }

    public string UOR_ID1 { get; set; }

    public string UOR_ID2 { get; set; }

    public string UOR_ID3 { get; set; }

    public string CUS_ID1 { get; set; }

    public string CUS_ID2 { get; set; }

    public string EST_ID1 { get; set; }

    public string EST_ID2 { get; set; }

    public string EST_ID3 { get; set; }

    public string EST_MANT { get; set; }

}

}
