
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class INVALIDCREDENTIALSLOG
{

    public int InvalidCredentialsLogID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public Nullable<bool> IsApproved { get; set; }

    public Nullable<bool> IsLockedOut { get; set; }

    public string IPAddress { get; set; }

    public System.DateTime LoginAttemptDate { get; set; }

}

}
