
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MOVIMIENTO_RFID
{

    public int cod_itemxmov { get; set; }

    public int act_id { get; set; }

    public string mov_codbarras { get; set; }

    public string mov_codLogicard { get; set; }

    public int mov_cusid { get; set; }

    public System.DateTime mov_fecha { get; set; }

    public string mov_hora { get; set; }

    public string mov_ip { get; set; }

    public string mov_portal { get; set; }

    public string mov_estado { get; set; }

    public Nullable<int> mov_antenna { get; set; }

    public Nullable<decimal> mov_NumAdicional1 { get; set; }

    public Nullable<decimal> mov_NumAdicional2 { get; set; }

    public Nullable<decimal> mov_NumAdicional3 { get; set; }

    public string mov_StrAdicional1 { get; set; }

    public string mov_StrAdicional2 { get; set; }

    public string mov_StrAdicional3 { get; set; }

}

}
