
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PAI
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PAI()
    {

        this.PROVEEDORs = new HashSet<PROVEEDOR>();

        this.PROVEEDORs1 = new HashSet<PROVEEDOR>();

        this.PROVEEDORs2 = new HashSet<PROVEEDOR>();

    }


    public int PAI_ID { get; set; }

    public string PAI_NOMBRE { get; set; }

    public int PAI_NIVEL { get; set; }

    public int PAI_PADRE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROVEEDOR> PROVEEDORs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROVEEDOR> PROVEEDORs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROVEEDOR> PROVEEDORs2 { get; set; }

}

}
