
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class POTENCIA_ANTENA
{

    public int potenciaID { get; set; }

    public Nullable<int> potencia { get; set; }

    public Nullable<int> antena { get; set; }

    public string reader { get; set; }

    public string estado { get; set; }

    public Nullable<int> sensibilidad { get; set; }

}

}
