
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PROVEEDOR
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PROVEEDOR()
    {

        this.ACTIVOes = new HashSet<ACTIVO>();

    }


    public int PRO_ID { get; set; }

    public string PRO_RAZON { get; set; }

    public string PRO_NOMBRE { get; set; }

    public string PRO_RUC { get; set; }

    public string PRO_CONTACTO { get; set; }

    public string PRO_DIRECCION { get; set; }

    public string PRO_TELEFONOF { get; set; }

    public string PRO_CELULAR { get; set; }

    public string PRO_FAX { get; set; }

    public string PRO_EMAIL { get; set; }

    public int PRO_CREDITO { get; set; }

    public string PRO_OBSERVACIONES { get; set; }

    public System.DateTime PRO_FECHAREGISTRO { get; set; }

    public int GRU_ID { get; set; }

    public int PAI_ID1 { get; set; }

    public Nullable<int> PAI_ID2 { get; set; }

    public Nullable<int> PAI_ID3 { get; set; }



    public virtual GRUPO GRUPO { get; set; }

    public virtual PAI PAI { get; set; }

    public virtual PAI PAI1 { get; set; }

    public virtual PAI PAI2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes { get; set; }

}

}
