
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class REPORTE
{

    public int REP_CODIGO { get; set; }

    public string REP_CODBARRAS { get; set; }

    public Nullable<int> CUS_ID { get; set; }

    public Nullable<System.DateTime> REP_FECHA { get; set; }

    public string REP_ESTADO { get; set; }

    public Nullable<int> ACT_ID { get; set; }

    public string REP_USUARIO { get; set; }

}

}
