
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UGEOGRAFICA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UGEOGRAFICA()
    {

        this.UORGANICAs = new HashSet<UORGANICA>();

        this.ACTIVOes = new HashSet<ACTIVO>();

        this.ACTIVOes1 = new HashSet<ACTIVO>();

        this.ACTIVOes2 = new HashSet<ACTIVO>();

        this.ACTIVOes3 = new HashSet<ACTIVO>();

    }


    public int UGE_ID { get; set; }

    public string UGE_NOMBRE { get; set; }

    public int UGE_PADRE { get; set; }

    public int UGE_NIVEL { get; set; }

    public string UGE_READERIP { get; set; }

    public string UGE_READERNOMBRE { get; set; }

    public string UGE_TIPOREADER { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UORGANICA> UORGANICAs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes3 { get; set; }

}

}
