
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UORGANICA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UORGANICA()
    {

        this.XCUORs = new HashSet<XCUOR>();

        this.ACTIVOes = new HashSet<ACTIVO>();

        this.ACTIVOes1 = new HashSet<ACTIVO>();

    }


    public int UOR_ID { get; set; }

    public string UOR_NOMBRE { get; set; }

    public int UOR_PADRE { get; set; }

    public int UOR_NIVEL { get; set; }

    public Nullable<int> UGE_ID { get; set; }

    public string UOR_CODIGO { get; set; }

    public string UOR_READERIP { get; set; }

    public string UOR_READERNOMBRE { get; set; }



    public virtual UGEOGRAFICA UGEOGRAFICA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<XCUOR> XCUORs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACTIVO> ACTIVOes1 { get; set; }

}

}
