
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class XCUOR
{

    public int XCU_ID { get; set; }

    public int CUS_ID { get; set; }

    public int UOR_ID { get; set; }



    public virtual CUSTODIO CUSTODIO { get; set; }

    public virtual UORGANICA UORGANICA { get; set; }

}

}
